### PR TITLE
WIP Design Cleanup

### PR DESCRIPTION
**Pull request by DLavin23**
@sisk @tshuck 

Don't merge, just wanted to get something up in case I get hit by a bus.

image

### CODE REVIEW

**Comment by tshuck** [comment]
Starting to look real real dope, Dan.  When'll this be ready to merge?

**Comment by DLavin23** [comment]
Was planning to bring in all your changes and merge this in tonight.

**Comment by DLavin23** [comment]
Orrrr the weather will be terrible and my flight will be delayed and I’ll get everything merged in before Monday.

**Comment by DLavin23** [comment]
@tshuck I merged in all the work you guys did on Tuesday, but I'm no longer seeing user songs added to the queue, is that expected as a result of PR https://github.com/tshuck/musicbox-react/pull/21? It looks like you [removed the `onClick` function ](https://github.com/tshuck/musicbox-react/pull/21/files#diff-cdef44c272934d7749bd8bd006572727L42)that handled that so I'm guessing the answer is yes. If so, then we can just merge this so we're not managing a divergent codebase. I just don't want to merge something that doesn't work as expected.

**Pull request merged**
