### PR TITLE
allows songs to be added to room queue

### PR DESCRIPTION
**Pull request by DLavin23**
@sisk @tshuck 

work from day 7

### CODE REVIEW

**Comment by DLavin23** [comment]
@tshuck did I jack something up? I could have sworn this was "working" when we finished this morning, but when I went back to add some design flair, I was getting errors.

image


Looks like my `roomId` is null....

**Comment by tshuck** [comment]
You're also getting 401 unauthorized -- probably because your token expired and we don't really handle that yet.  You... gotta go clear out local storage to get it to let you re-auth at the moment.

**Comment by DLavin23** [comment]
I'm an idiot

**Comment by tshuck** [comment]
I'm around for a bit if you get stuck -- was gonna see about "joining" a room so that we don't have to hard-code the room id like we're doing now.

**Comment by DLavin23** [comment]
Thanks for the offer, but I'm probably going to save it for the AM since I'm about that early morning lyfe.

**Pull request merged**
